[package]
name = "otrs"
version = "0.1.0"
authors = ["xumarcus <xumarcus.sg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.rand]
version = "0.8.2"
features = ["small_rng"]

[dependencies.clap]
version = "3.0.0-beta.2"

[profile.release]
# For profiling
# debug = true

# Link-time optimization
lto = "fat"

# Optimize across chunks
codegen-units = 1
