[package]
name = "wasm"
version = "0.1.0"
authors = ["xumarcus <xumarcus.sg@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.63"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

# wee_alloc reduces wasm size
# wee_alloc = { version = "0.4.5", optional = true }

# Main lib
othello_multimcts = { version = "^0.1", path = "../" }

# Requires "js" when targeting wasm
getrandom = { version = "^0.2", features = ["js"] }

# For Date.getTime
js-sys = "^0.3"

rand = "^0.8"

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
# Tell `rustc` to optimize for small code size.
# opt-level = "s"

# Performance more important?
opt-level = 3
